name = Wrappers
description = Zones are back! Susy! Yeah!
preview = preview.png
template = wrappers-layout

; Regions
regions[header]         = Header
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[breadcrumb]     = Breadcrumb
regions[highlight]      = Highlight
regions[preface]        = Preface
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[postscript]     = Postscript
regions[footer]         = Footer
regions[footer_sub]     = Footer Sub

; Stylesheets
stylesheets[all][] = css/layouts/wrappers/wrappers.layout.css
